### ISSUE TITLE
[SPIKE] Auto location for physical address

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#124]
The USPS API looks promising because it is free use and should meet out capacity. Also if it isn't validated by USPS we won't be able to deliver mail to that address anyway.

API documentation here:
https://www.usps.com/business/web-tools-apis/welcome.htm#api
**Don't** use the other documentation on the site, it's outdated or wrong. 

URL:  https://stg-secure.shippingapis.com/ShippingApi.dll 
we want to use the `Verify` endpoint

## Considerations:

We will want to do the validation server-side so that the API keys are not exposed excerpt from [developer guide](https://www.usps.com/business/web-tools-apis/general-api-developer-guide.pdf):  "This user ID is not to be shared with others outside your organization, nor is it to be packaged, distributed, or sold to any other person or entity". 

ISO-8859-1 encoding is the expected character set for the request. Make sure that special
characters embedded in any tag data such as & < > are escaped and url-encoded. 

One key per website

## Form fields we will want to use
To be compatible with this API we will want the following fields (The fields have to match but they don't have to be labeled in this way for the user)

Required:
 - Address 1
 - Address 2
 - City
 - State
 - 5-digit zip (0 if )

Generated:
 - +4-digit zip (we don't have to ask for this, we should be able to get this from the API)

We will want fallback behavior if the postal API is down

Optional:
We will want to decide if an how we ask for the optional data
 - Urbanization - a field for PR addresses
 - Delivery route 
 - Carrier route

## Questions
Oddly enough the API doesn't ask for Country but seems to validate international addresses since there is instructions for international 

## Sample call 
```
<AddressValidateRequest USERID="XXXXXXXXXXXX">
<Revision>1</Revision>
 <Address ID="0">
 <Address1>SUITE K</Address1>
 <Address2>29851 Aventura</Address2>
 <City/>
 <State>CA</State>
 <Zip5>92688</Zip5>
 <Zip4/>
 </Address>
</AddressValidateRequest>
```

**Comment by LindsayYoung** [comment]
The USPS API looks promising because it is free use and should meet out capacity. Also if it isn't validated by USPS we won't be able to deliver mail to that address anyway.

API documentation here:
https://www.usps.com/business/web-tools-apis/documentation-updates.htm
Specifically, the address API
https://www.usps.com/business/web-tools-apis/address-information-api.htm

## Considerations:

We might want to do the validation server-side so that the API keys are not exposed excerpt from [developer guide](https://www.usps.com/business/web-tools-apis/general-api-developer-guide.pdf):  "This user ID is not to be shared with others outside your organization, nor is it to be packaged, distributed, or sold to any other person or entity" but I am taking a look at some client side code. 

ISO-8859-1 encoding is the expected character set for the request. Make sure that special
characters embedded in any tag data such as & < > are escaped and url-encoded. 

One key per website

## Blockers

Tried to [register a key](https://registration.shippingapis.com/) to test out the API and it threw an error.

**Comment by Jacklynn** [comment]
- Next step: decide if we want this to be in the first slice/ATO?

**Comment by LindsayYoung** [comment]
Went over research with @UchMok 

We will some good error messaging for incomplete Addresses; like a message when there is a missing unit number. We need to figure out fallbacks for when the API doesn't validate, when it comes to mailable things, the API seems stricter than the post office. 

Also, I have some code that we can use later but not sure where to put it.

**Comment by LindsayYoung** [comment]
I am not closing this since it needs to be used as reference for the future location work
