### ISSUE TITLE
Tell DOJ CRT what characteristics (protected class) I think influenced the victim's treatment

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#127]
## Narrative
As a public User
I want to select if a specific characteristic (protected class) affected why I was treated this way
So that I can give more context to my situation and allow CRT to best asses what happened to me.
and
I understand the value of providing this information, via the help text on the page (ie: _"Civil rights laws protect people from discrimination and include these protected classes."_)

## Background
Complainants are asked to indicate why the believe the discrimination took place through a list of protected classes that represent the statues that CRT enforces. This information helps route the complaint to the correct section, determine merit and help sections find patterns.

The list of protected classes also helps the user understand what information is helpful to include in a complete complaint.

## Assumptions
This is a required field for the complainant so there will be at least 1 protected class selected. 

The user can check multiple protected classes.

If the user doesn't identify a protected class, they should choose "Other reason" and will be prompted to explain in a required freeform text box.

Most public users will not know the terminology "protected class," so we shouldn't rely on the phrase without further context for users.

## Out of scope
Including specific list of disability subclassifications Enhancement issue here

Glossary definitions of the protected classes

## Acceptance criteria

1)
Given I'm a public user filling out the complaint intake form
after I have filled out (or not filled out) my Contact Details on step 1 of the form AND hit "next"
Then I view that
- I am on step [2] called "Protected Class" (bubble is filled in)
AND
- I view that the 'Freeform' step is after 'Protected Class' step on the workflow
AND
- I am on a page called 'Please provide details' (refer to Mockup for full content and spacing expectations)

AND
- I view a question that asks, "Do you believe you were treated this way because of any of the following characteristics or statuses that apply to you?" 
- I view help text below that says, "Civil rights laws protects individuals from being discriminated against based on race, color, sex, religion, and other characteristics." 
- I view a list of protected classes that I can check

- [ ] Disability (including temporary or in recovery)
- [ ] Race/color
- [ ] National origin (including ancestry, ethnicity, and language)
- [ ] Immigration/citizenship status (choosing this does not share your status)
- [ ] Religion
- [ ] **Sex or gender identity (including gender stereotypes) or pregnancy** _Update requested by EOS_
- [ ] Sexual orientation
- [ ] **Family, marriage, or parental status**
- [ ] Military status
- [ ] Age
- [ ] Genetic information
- [ ] Other reason (please describe)

- I view options to move forward/back on this form

2)
Given I'm a public user filling out the complaint intake form
if I do not select any of the options from the list AND click NEXT
I will see an error message that says, "Please make a selection to continue. If none of these apply to your situation, please select "Other reason" and explain"
AND I won't be allowed to move to the next step

3)
Given I'm a public user filling out the complaint intake form
if I select "Other reason"
I will view a freeform text box (word limit of 10) where I can briefly explain
and a word counter below the text box that says, "10 words remaining"

4)Given I'm a public user filling out the complaint intake form on step 'Protected class'
WHEN I selected 1 or more of the check boxes AND click Next
THen I move to the next step of the intake form called 'Freeform'

## Questions:
- Do sections approve of the phrasing of the question.
- Do we have all of the classes we need in this list?
- Is the order meaningful and do we agree on it?

## Design Mockups

https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/60
#### First View
![image.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/b8f6fa64-1912-4beb-8ec9-58ee912b0b3b)
#### 'Other Selected View'
![image.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/f1a52a6f-22aa-4e7b-85bb-598769e097c4)
#### Annotations
![image.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/6d4fa9d0-d2e5-41d1-90cf-dad13061c661)
![image.png](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/cd05806d-6c2f-4a8c-982b-13f36b71619c)

## Technical notes
We'll want to remove the model level validation so we can save the "other" text.

**Comment by Jacklynn** [comment]
![Class Copy 11.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/dc36fb00-04f5-4434-ad55-022a91aef505) Idea for including the text from "Other" but I feel like it would be so varied that it might be worth just opening the detail page, but open to others' thoughts

**Comment by UchMok** [comment]
@Jacklynn is this the UX for #130

**Comment by Jacklynn** [comment]
oops!

**Comment by Jacklynn** [comment]
Of the pages we have...

1. Protected class
2. Free form
3. contact

**Comment by alexsoble** [comment]
Decision: let's reuse the same UI alert pattern that we used for the Details page and see if it works.

**Comment by alexsoble** [comment]
We want the text in the "Other reason" text field to stay there after the "Other reason" checkbox is unchecked — let's see if that behavior is supported by default.

**Comment by alexsoble** [comment]
If the user checks "Other reason," then the "Please describe" field is mandatory, not optional.

**Comment by LindsayYoung** [comment]
@AvivaOskow "This is a required field for the complainant so there will be at least 1 protected class selected." Aren't there cases like voting right where there might not be a protected class?

**Comment by LindsayYoung** [comment]
page 2 of current 3

**Comment by Jacklynn** [comment]
@LindsayYoung we talked about it during story time today but Bill thought that "other" would be a good way to catch Voting scenarios too because they should still feel like a reason something happened "voting place closed early"

Other notes:
* Suggesting updating the text to: `Do you believe you were treated this way because of any of the following characteristics or statuses that apply to you?` (from writing lab)
AND
subtext: `Civil rights laws protects individuals from being discriminated against based on race, color, sex, religion, and other characteristics.` to remove mentions of protected class
* Update error message to remove protected class mention: `Please make a selection to continue. If none of these apply to your situation, please select "Other reason" and explain`
* Suggest alluding to the fact that someone can say more when selecting other: `Other reason (please describe)`

* Bill will send out text before UAT so they have time to review as well

**Comment by Jacklynn** [comment]
I noticed some of the text was inconsistent with the master content doc and updated the list above

FYI @AvivaOskow @LindsayYoung

**Comment by Jacklynn** [comment]
Notes:
* Don't want to encourage people to add bad data by using "other" if they don't feel like the options above fit them
* optional could be caught by CRT users to enter a class

**Comment by alexsoble** [comment]
Code reviewed with @ilodidoj, see code review on GitHub: 

https://github.com/usdoj-crt/crt-portal/pull/91/#pullrequestreview-305292310

**Comment by alexsoble** [comment]
First PR on this Story from @LindsayYoung moved through code review and merged:

https://github.com/usdoj-crt/crt-portal/pull/91

This covers the Acceptance Criteria, database layer, and first pass at front end.

Next, I'll open a new PR to handle remaining front-end issues with spacing/padding and "Other" input styles.

**Comment by alexsoble** [comment]
PR `114` includes a variety of front-end updates to better match the specs. See more information, TODOs and screenshots below:

https://github.com/usdoj-crt/crt-portal/pull/114

## What does this change?

+ Add blue highlight to the "Other" field as per the design spec.
+ Update spacing to match the design spec. 
+ Fix small bug with leading whitespace on checkbox labels.
+ Update HTML so that all `<div>` and `<label>` tags are closed. 
+ Simplify logic in HTML template for `report_class.html`. 
+ Uncomment/restore connecting line in progress bar wizard. 

## What issues does this NOT address? 

+ A11Y issues and browser compatibility issues: 
  + We learned from our review session with Terri Youngblood that there are multiple a11y issues to address, such as the error message not announcing properly and a more descriptive label required for "Please describe 'other'." 
  + The review session also surfaced IE compatibility issues, such as the word count function not working in Terri's IE browser.  
+ Alert state visual placement / design requires further conversation.
+ Checkboxes are not completely aligned with label text — designs show label text being one line only, but at our current form width the text spills over into a second line. Should we consider widening our `usa-form` element max width to `40rem`? Some discussion required. 
+ Checkboxes are not completely flush left. 

## Screenshots:

![page2](https://user-images.githubusercontent.com/3209501/67513886-6055b100-f661-11e9-9c22-c92eb61c9ec2.png)

### "Other" checked state

<img width="713" alt="other-checked-state" src="https://user-images.githubusercontent.com/3209501/67515875-2be3f400-f665-11e9-84c7-e2589482f8f1.png">

**Comment by alexsoble** [comment]
**Dev/design sync notes!**

+ Discussed server side vs client side errors
+ For Protected Class server side errors, we made the following decisions with @LindsayYoung @AvivaOskow and @Jacklynn!
  + Use red error style rather than yellow warning. Warning versus error styles have different icons. 
  + Summary of errors at top of page. "1 error: Protected Class."
  + More detailed error message directly below the associated form element, in this case directly below the "Other" checkbox.

**Comment by alexsoble** [comment]
@AvivaOskow caught that the checkbox color is a bit off.

**Comment by alexsoble** [comment]
Copy change from @AvivaOskow: "Please provide details on what happen" > "Please provide details"

**Comment by lalitha-jonnalagadda** [comment]
Notes from desk review 
- Expecting content changes. Source of truth to be updated with the latest and greatest content changes
-  Change 'Other' to 'Other Reason'
-  Additional Color changes based on designer feedback

**Comment by lalitha-jonnalagadda** [comment]
The word counter bug #166 is now fixed and this story is good to be 'Ready for the UAT'.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we finished review with the deep dive group.
