### ISSUE TITLE
View 'Violation Summary' in View All Complaints Table

### ISSUE THREAD

**Issue by UchMok** [18F/crt-portal#129]
## Narrative
As a DOJ CRT user
I want to view violation summaries in the 'View all Complaints' Table
So that I can make quick confirmations of multiple complaints' merit to confirm ownership and actionability 

## Background
The violation summary allows DOJ CRT to determine whether a complaint has merit. Historically, CRT has received violation summaries that are not helpful in determining merit, because they are too verbose (+30 pages) or vague.

A lot of users used to rely on attachments to explain their incident and tell CRT to 'see attached'. This field will direct them to 'use their words' to fully describe their problem.

This user story will allow CRT users to view abridged summaries of complainant's problems. Eventually, the CRT users would like to be able to view the full summaries of multiple complaints on the view all table via 'hover' or 'tool-tip' functionality.

Some CRT users like to filter by keywords in violation summaries (eg 'service animal) when sorting through complaints

## Assumptions
- CRT users don't need to view full summary on view all table for this specific story
- eventually, once filter sort is applied, CRT users will be able to also filter/sort on this column

## Out of Scope
- hovering, tool tip, or expanding on data table element to view full summary
- filter or sort

# Acceptance Criteria
1)
Given a Complainant has submitted a complaint *w/* a violation summary via the online portal
When I log in to view the 'View All complaints' table
Then I view a column to the right of Contact details called 'Violation summary'
AND
I view only 120 characters of that complainant's violation summary in the column.
- string values 
- ellipses to follow abridged summary (static, no tooltip or text expansion) 

2)
Given a Complainant has submitted a complaint *w/ out* a violation summary via the online portal
When I log in to view the 'View All complaints' table
Then I view a column to the right of Contact details called 'Violation summary'

## UX
[Deck here] (https://docs.google.com/presentation/d/1k0HWEhcIb6QC5fXNaXmePqoFpKau6_d-mZL2Q4DCa-w/edit#slide=id.g60c2d2cb07_0_83) (update sept 25)

![ViolationSummary_Sept25.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/808fa03f-f30b-41f8-9307-c90285398245)

**Comment by UchMok** [comment]
@Jacklynn @AvivaOskow please review and complete the story. Need input on # of characters to view initially in this column.

**Comment by LindsayYoung** [comment]
I noticed the ACs say "blank" but the mocks ask for an em-dash. Wanted to confirm this was an intentional design change and if so, does that apply to the rest of the page. UX guide for that page is here: pagehttps://docs.google.com/presentation/d/1k0HWEhcIb6QC5fXNaXmePqoFpKau6_d-mZL2Q4DCa-w/edit#slide=id.g41bfb1d907_0_8

Also, or reference, the current cutoff is 125 characters. So, you can use that as a guide if you want it longer or shorter. FYI: the length of the text it is going to be much more consistent and easier to implement going with characters instead of words.

**Comment by Jacklynn** [comment]
Thanks for noting the inconsistencies, I updated the ACs to those changes. +1 to using an em dash, and to using the character limit.

**Comment by Jacklynn** [comment]
Not a big deal, but I think I originally was originally testing with 120 characters, but the 5 characters don't seem to effect the row length right now

Updated documentation (also linked above) https://docs.google.com/presentation/d/1k0HWEhcIb6QC5fXNaXmePqoFpKau6_d-mZL2Q4DCa-w/edit#slide=id.g60c2d2cb07_0_83

We also talked about peppering in some design changes throughout, I've listed some that I felt were light weight out here (next slide) based on Aviva's sketch file: 
https://docs.google.com/presentation/d/1k0HWEhcIb6QC5fXNaXmePqoFpKau6_d-mZL2Q4DCa-w/edit#slide=id.g63b7160d03_0_19

**Comment by blaughman** [comment]
The submission form works in IE11.  One thing I am noticing is that you are able to enter numeric characters and other symbols in the contact first name and contact last name fields.

**Comment by LindsayYoung** [comment]
Hi @blaughman for name validation, we don't really want to lock it down for a few reasons. One is that when this gets translated it will need to accept other language characters. Secondly, people have a wide variety of names, sometimes only one, there are one-letter names, sometimes names might be punctuated etc. I don't know of cases with numbers but I rule that out as a possibility. Unlike other fields, adding rules to name fields doesn't buy you much data quality because someone will still file as "Seymour Butz." But, people can get offended or upset if you tell them their name is wrong and it isn't. Here is a link about considerations about name fields- if you are interested. https://www.w3.org/International/questions/qa-personal-names.en#fielddesign Though, if you still want to take out numbers we can.

**Comment by blaughman** [comment]
Lindsay,
Uchenna and I spoke about this on Friday and she told me why it was important not to limit the character types.  So, I’m fine with how we have it and, as always, you make a clear case on why it should be as it is.

**Comment by lalitha-jonnalagadda** [comment]
@LindsayYoung  and @blaughman  looks like the the functionality is working as expected. Are we good to move this card to UAT?

**Comment by Jacklynn** [comment]
@LindsayYoung I think if we took off the banner (how you know this is a gov website) and footer it would feel more like a web app and less like a website.

**Comment by Jacklynn** [comment]
Made PR to update title to "Summary" https://github.com/usdoj-crt/crt-portal/pull/129

**Comment by LindsayYoung** [comment]
Updted AC 2 "I view blank for that complainant's complaint record in that column, indicated by an em dash —" this is a required question so there will be no blanks.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card as we finished review with the deep dive group.

**Comment by lalitha-jonnalagadda** [comment]
Closing this card. This functionality is deployed on staging and prod already.
