### ISSUE TITLE
Style Changes -- Sprints 5, 6, 7

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#168]
### Columns

+ [ ] Update columns to reflect style guide

### Protected Class page

+ [x] Fix spacing around helptext on Protected Class page
+ [x] Adjust checkbox background color to match our standard dark blue

**Comment by Jacklynn** [comment]
![Screen Shot 2019-10-31 at 8.32.18 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/dd5f17e7-8228-49a0-bd30-223ef1b81614)

Looks fixed to me, thanks so much Alex!!

**Comment by alexsoble** [comment]
We want to update the site to use the USWDS grid system as laid out in our style guide; @AvivaOskow has created a mockup w/ annotations for how this should look on desktop, and once we have a mockup for mobile I will translate both into code.

**Comment by AvivaOskow** [comment]
## USWDS 12 column grid:

### Desktop
For desktop, the content would be left aligned to the third column. I'm proposing that headers are allowed to take up 8 columns and the content below can take up 7 columns at most (for smaller field inputs they don't always need to take up the full 7 though.

[Screen Shot 2019-10-25 at 4.45.32 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/b7b39f40-8d80-42e2-a9a2-8e8584f6756b)

--- 

![Screen Shot 2019-10-25 at 4.47.34 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c5469748-6df6-432d-a4f6-b51fb48762d6)!

### Mobile
Most things on mobile will use all 12 columns, however I'd like to work together to figure out how to make certain elements looks ok, like the primary issue boxes for example. Most of the fonts and vertical spacing stays the same, like on on the contact page below, but the Primary Issues page needs a little more customization to fit well on mobile (for example, 24 pixels above and below the intro text instead of 32 on desktop) but if this is too complicated to customize now, I'm open to waiting or thinking of another solution.

![Screen Shot 2019-11-21 at 4.03.06 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/42d03add-a4db-4d77-bd0e-7034e38a2729)

--- 

![Screen Shot 2019-11-21 at 4.08.10 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/fbdba8cb-f9ee-452d-b70b-fe041d381bca)

---

![Screen Shot 2019-11-21 at 4.03.51 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/f2f57da5-5657-4d72-9fb7-aefbd4b35da3)

**Comment by lalitha-jonnalagadda** [comment]
We are working in new designs for this page anyway and would need to address style  changes with the improvements. Good to close this card
