### ISSUE TITLE
Tell DOJ CRT If I am an active duty service member

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#196]
## ## Narrative
As a public user, I want to tell DOJ CRT if I am (or have been) an active duty service member so that they can appropriately route and take action on my complaint. 

## Business Context
Active duty service members are protected by certain statutes enforced by CRT.  Many service members may not be aware of the protections afforded to them by the statutes.  Extracting this information will allow VOT, EMP and HCE to determine if any of the statutes may apply to a complainant.

## Assumptions
- This is a required question

## Out of Scope
- Routing to sections

## Acceptance Criteria

1) Given that I'm on the contact page
Then
I see a new question -  'Are you now or have ever been an active duty service member?' 
AND 
I can optionally enter my contact information

2) Given that I'm on the 'Contact' page
When I see  'Are you now or have ever been an active duty service member?' 
Then I see that I can make a 'Yes' or 'No' selection

3) Given that I'm on the 'Contact' Page
When I make a selection for the 'Are you now or have ever been an active duty service member?' 
Then I see that my selection is visually represented by the radio button being selected

4) Given that I'm on the 'Contact' Page
When I DON'T make a selection 'Are you now or have ever been an active duty service member?' and click 'Next'
Then I see an alert - 'Please select your status as an active service member' 

5) Given that I'm on the 'Contact' Page
When I make a selection for 'Are you now or have ever been an active duty service member?' and click 'Next'
Then I'm taken to the 'Primary Issues' page

6) a11y requirements
This should be a generic check box interaction.
As a screen reader user, when I get to this question, I hear the question and options.
AND
I can tell when something is and isn't selected
AND
I can navigate & select using keyboard only
[documentation](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

## Mock ups
![All Contact-annotations.jpg](https://images.zenhubusercontent.com/5b34455c5b51b10bd4dd59d6/ca54143b-1d82-413b-b277-83d8b1d5d377)
Source of truth: 
https://docs.google.com/document/d/1bxSRc9CQOHjQhTaYkHncE4tykUEFeC6RzFtP5IQk0Ic/edit?ts=5de6f69e

### Sign Off
Story sign off
- [ ] PO
- [ ] HCE
UAT sign off
- [ ] PO

**Comment by Jacklynn** [comment]
HCE requested moving service members question at a higher level because it affects other sections.

![All Path - Protected class + service members.jpg](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c3c4c31c-bf48-4a73-9805-888b4e3bf1d1)

**Comment by Jacklynn** [comment]
Noting additional feedback:

Screen 2
-I understand that one of the options is “Housing discrimination or harassment” but some people may not connect “sexual harassment.”  Can you add another bullet that reflects something like: “Sexual harassment by a landlord or management employee?
-I’m concerned that “Harmful living conditions or lack accommodations for disability” may send the message that we’re interested in things like mold or other slum-lord type of complaints.  Can we amend this to reflect “Unit needs modifications for disability, accommodations needed for disability, or service animal-related issues?”
-Also, this list does not address familial status.  Can we add something like: “Minor children issue?”
-I noticed I am unable to check more than one option on the first screen after the contact screen.  Is this by design?

Screen 4
-The introductory note: “Some civil rights laws protect people from discrimination, which include these protected classes. These are some of the most common classes that we see,” may need to be amended to reflect “Some civil rights laws protect people from discrimination, which include these protected classes. These are some of the most common classes.”  (deleting “that we see”)
-Can we add “Sexual Harassment?”
-Age is not a protected class under the FHA (or any of the statutes we enforce).  This should be removed from Housing’s list.

**Comment by Jacklynn** [comment]
"Active duty service member"

**Comment by blaughman** [comment]
Function works as intended in IE 11 and Chrome.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Showcased during deep-dive on 2/6.
