### ISSUE TITLE
Footer details 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#318]
The footer of the form should have all these mandatory links - https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/

### Contact

info |link
---|--- 
U.S. Department of Justice|
Civil Rights Division|
950 Pennsylvania Avenue, NW|
~~Office of the Assistant Attorney General~~|
Washington, D.C. 20530-0001|
~~(202) 514-4609~~      |~~"tel:202-514-4609"~~
Telephone Device for the Deaf|
(202) 514-4609 |"tel:202-514-4609"

phone number is updated
### Links

info |link
---|--- 
About the division |https://www.justice.gov/crt/about
Report a violation |https://civilrights.justice.gov
En Español |toggle to spanish
Privacy policy |Link to come
FOIA |https://www.justice.gov/oip
Accessibility |https://www.justice.gov/accessibility/accessibility-information
Justice.gov |https://www.justice.gov/
Office of the inspector General  |https://oig.justice.gov/
Budget and performance |https://www.justice.gov/doj/budget-and-performance
USA.gov |https://www.usa.gov/
USAGov en Español |https://www.usa.gov/espanol/

Links that are required but not in the mock:
- https://www.justice.gov/doj/budget-and-performance
- https://www.usa.gov/
- https://www.usa.gov/espanol/ was encouraged but not technically required

I have omitted two links we don't have content for, correct me if I am wrong: 
- Already Submitted?  - has not built this out, will be available when the landing page is in
- Your Rights - has not been built yet

# Mockups

Mockup and Annotations [here](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/52)

**Comment by Jacklynn** [comment]
@lalitha-jonnalagadda https://digital.gov/resources/required-web-content-and-links/

**Comment by AvivaOskow** [comment]
@lalitha-jonnalagadda here is a first pass at the footer. We should discuss with CRT what links we actually want to have here. I included the mandatory ones, but we should discuss what should be on here vs regular justice.gov/crt

![Screen Shot 2020-04-27 at 2.37.53 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c3b37d37-dcc7-4fb2-b7c0-1a5fa1c0101a)

**Comment by Jacklynn** [comment]
Ooo! Looks so official! 

I think the all caps is a little hard to read, but if this is a pattern elsewhere I'll be quiet :)

**Comment by cantsin** [comment]
Side note, the `Telephone Device for the Deaf` phrasing is a bit odd to me, usually it's either `Telecommunication Device for the Deaf` or `Text Telephone`. I know there's no standard here, but wanted to point that out.

**Comment by AvivaOskow** [comment]
@cantsin I pulled that directly from the existing justice.gov contact info, but happy to change it if we should!

**Comment by AvivaOskow** [comment]
@lalitha-jonnalagadda Updated footer here:

![Screen Shot 2020-05-08 at 3.09.19 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/3f66eadc-e507-4bbf-b142-93cdbdf6aea3)

_@Jacklynn I tried doing sentence case instead of all caps, just to compare. but it is a pattern elsewhere (check out the FOIA.gov footer! But I'm open to changing)_

**Comment by cantsin** [comment]
> happy to change it if we should!

Ah, I didn't realize that the wording came from justice.gov. In that case, let's leave the phrasing as-is. Thanks.

**Comment by Jacklynn** [comment]
@AvivaOskow I think the all caps actually look more like links/interactive. Thanks for playing with it though! You are the best person and designer.

**Comment by cantsin** [comment]
Regarding the "en Español" link in the mockups: the built-in Django library we are using requires a POST to the `set-language` url. Because we are submitting a form, I think this is properly rendered as a dropdown, not a link. Would leaving the language dropdown as-is work for y'all? 

The alternative is doing something like ... `{% if LANGUAGE_CODE == 'en' %}`, adding a button and restyling it to look like a link, which seems a brittle to me. (CC @Jkrzy -- maybe he has ideas on this front)

**Comment by cantsin** [comment]
Side note, I am not wrapping "USA.gov" and "Justice.gov" and "USAGov en Español" in translation blocks (... what would these translate to?) but please let me know if this assumption is incorrect.

**Comment by Jacklynn** [comment]
@cantsin not translating those links works for me. 

The drop down is ok (@AvivaOskow feel free to contradict me) but I suspect it might need to be styled or it'll feel a little out of place 😅

**Comment by cantsin** [comment]
Here's what I have currently -- ignore the icons, they are placeholder only until I have the correct ones.

![2020-05-11_16-47.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/ce808027-111c-46a8-92c0-f1168517bb79)

I see nothing wrong with the language dropdown 😅

**Comment by Jkrzy** [comment]
The session approach we have now was the quickest path to provide a minimal debugging functionality to switch languages. Please don't consider it set in stone 😅 

[Another implementation approach](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#url-internationalization),  Django provides is including a language identifier in the URL. 

1. Would make it possible to render that as a regular old <a> tag.
2. Would prepend `es` to Spanish versions of site, e.g. `https://crt-portal-django-dev.app.cloud.gov/es/report/`

There some advantages to this approach, like being able to link from another site or otherwise navigate directly to the Spanish version. Checkout the earlier link to the Django documentation for an example of it in action.

**Comment by cantsin** [comment]
Ooh, thanks! I missed this -- yes, doing language identifiers in the url could work. That being said, I believe doing so is out of scope for this ticket, though. Happy to do this work in a separate PR if we agree it is worthwhile (and a priority item?)

**Comment by Jacklynn** [comment]
@cantsin amazinnggg!! So fast! One change is that I think the links should be `text-transform: uppercase` to make it more obvious that they are links, per Aviva's first version 14 days ago (in comments). I had suggested the alternative version, but I think her first version is clearer.

**Comment by Jacklynn** [comment]
@AvivaOskow what do you think about moving the language picker to the other side since it's not really a link if it's a drop down. 

<img width="1004" alt="Screen Shot 2020-05-11 at 5 45 01 PM" src="https://user-images.githubusercontent.com/2560618/81625982-4be3c680-93af-11ea-8c2f-1ba8c3109e57.png">

**Comment by cantsin** [comment]
As per @LindsayYoung we want the privacy policy to open in a new tab/window -- any other links that should do so, as well?

**Comment by AvivaOskow** [comment]
@Jacklynn @cantsin if we are adding a dropdown button, can we style it? What about something like this?

![Screen Shot 2020-05-12 at 3.51.38 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d424edeb-2994-47ad-b03b-9b806b435a15)

**Comment by cantsin** [comment]
We can certainly style the drop-down with the caveat that it may look different across browsers/mobile. I'll give it a shot and see how IE11 looks.

**Comment by AvivaOskow** [comment]
@cantsin thanks! I also tried this version, if we think it stands out better

![Screen Shot 2020-05-13 at 12.27.29 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/8590719c-578e-4b43-9e69-49d2ca81987b)

**Comment by cantsin** [comment]
I think we still need the button to submit the language change. (We can auto submit when a dropdown is selected, but I believe this is not best practice.) Played around with this a bit, looks OK in IE11/Edge. Ended up with:

![2020-05-13_10-53.png](https://images.zenhubusercontent.com/5eb05c8e896abe15ccf6dfa3/b78c6a1f-5e67-4025-afee-c81567fe6481)

Side note, links section is now unbalanced because we had to remove `Already Submitted?` and `Your Rights` since they are not going to be in for this launch. Happy to change any of this...

**Comment by AvivaOskow** [comment]
@cantsin this looks amazing! I feel like you don't even need my annotations 😄but I have the issue open right now and am uploading, but I don't think you'll need to change much. 

For the links, my suggestion is to move FOIA and ACCESSIBILITY to the left column, and JUSTICE.GOV/CRT to the right at the top of the list

@Jacklynn what do you think about the language interaction?

**Comment by AvivaOskow** [comment]
Ok @cantsin the annotations are up [here](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/52) and I'll upload the icons asap

**Comment by AvivaOskow** [comment]
@cantsin this is looking great! 

## **Some small fixes:**

- [ ] Can we put the contact info to the right of the icons instead of below?
- [ ] Can we make the language picker shorter and put the "Go" button next to it instead of below? And make that button yellow (Or make the dropdown yellow and the button a white outline, I'm on the fence about which is better)
- [ ] The mockup uses 14px font but we are using 16 px (the links all fit on one line at 14 on desktop) but I'm fine with leaving this for now, since maybe there is a benefit to it being larger anyway. @Jacklynn do you have a preference?

![Screen Shot 2020-05-14 at 12.25.02 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/8fcefcd5-5bae-4a3d-8c66-56773eb230f8)



### Button options

![Screen Shot 2020-05-14 at 12.34.46 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/d14ef63a-636a-46f8-a809-e24a6d8748f0)

![Screen Shot 2020-05-14 at 12.34.56 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/e6a8e0f1-717d-4c70-afe5-22cbc934106f)

**Comment by cantsin** [comment]
@AvivaOskow for sure. this breakage was not intentional -- the release to dev didn't pick up some of the newer style changes for some reason. will be looking at this shortly -- please hold off on any further review until we get dev sorted out.

**Comment by Jacklynn** [comment]
14px looks more expected to me too, I played around with it in dev.

I know this is in flux and not to spec yet, but just noting the button now doesn't meet contrast requirements with the background. 
![Screen Shot 2020-05-14 at 9.56.32 AM.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/c559dae3-3403-4f9e-a9cd-24e9b1c78a22)

**Comment by AvivaOskow** [comment]
@cantsin it's looking great! I have a few small things but I think they aren't priority probably.

### Highest priority:
- [ ] The font size should be 14 px, 1.5 leading (I had it as 1.7 but I think we use 1.5 for 14 px elsewhere so making it match would be good)

### lower priority:
- [ ] The globe icon looks smaller than the others, but maybe it's a optical illusion

### later, but important priority:
- [ ] The Civil Rights 'logo" font looks wonky to me (too bold) but this is something we've dealt with before and haven't totally fixed, so I want to maybe have a separate small ticket for this across the site.

**Comment by cantsin** [comment]
Font size: fixed in https://github.com/usdoj-crt/crt-portal/pull/476

Globe: You have sharp eyes! Globe icon is indeed smaller (21px) compared to the others (24px). I think this is a consequence of the IE11 tweaks we did, will see if I can force it back to its normal width.

Logo: separate ticket sounds good.
