### ISSUE TITLE
Filter bug (nonce issue)

### ISSUE THREAD

**Issue by LindsayYoung** [18F/crt-portal#334]
The backend filters are not working because the nonce value for the inline JS is not being rendered by the template.

- This can be reproduced locally if you add the middleware and nonce settings globally. 

It doesn't make sense to me because it works on the front end:
https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/templates/forms/report_base.html#L71 

But the same template tag does not work on the backend:
https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/templates/forms/complaint_view/index/index.html#L57

**Comment by Jkrzy** [comment]
Having some trouble replicating this locally but the nonce does appear to be generating as expected in the template -- devtools does however hide it from the Elements inspector.

You can see it w/ the `Sources` tab if you view index.html there.

It looks like it's failing because `data` isn't an allowed source in our current CSP config. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
