### ISSUE TITLE
Design audit: Desktop progress bar fixes

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crt-portal#375]
## **Issues:** 

- Circle outline around numbers looks too thick 

- Sometimes the numbers don't look centered in the circles—too low (but not on every page? This might have been fixed already)

- Progress bar gets too close to element below at small browser / tablet size

- Left alignment of text under each circle makes it look misaligned

## **Changes:** 

- [x] White circle outline should be 1 px, not 2 px (should be same width as horizontal line behind it)

- [x] Center numbers evenly in circles

- [ ] Maintain same spacing between progress bar and box below (except in mobile, can be smaller)

- [x] Center align text to each circle

### **Current**
![Screen Shot 2020-03-19 at 1.53.23 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/0d653edf-e2ce-40f6-881f-125b9633aad3)

**Number centering issue**

![Screen Shot 2020-03-16 at 2.38.40 PM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/a1cdc03c-d016-4de5-90dd-a00b67b0000c)

--- 

### **[Spacing annotations here](https://app.zenhub.com/workspaces/doj-crt-form-design-flows-5d7a67fa86a8cd0001581ea0/issues/18f/crt-django/40)**

![Screen Shot 2020-03-19 at 1.58.51 AM.png](https://images.zenhubusercontent.com/5846f186b9dc3c6220230bf1/c58b1ff6-ecb8-4df0-b1e8-137c6d15d1d0)

**Comment by AvivaOskow** [comment]
Are we planning on making the steps clickable at any point?

**Comment by LindsayYoung** [comment]
Also, screen readers on ProForm (form/new) reads “current state” “completed” progress bar. This makes sense for the public form, but when this is no longer a multi step form, it shouldn't read status.

**Comment by LindsayYoung** [comment]
@AvivaOskow we can't do the form steps, past the step the user is on because we don't know which pages they need to fill out until they have a primary issue. If we did just give them the generic questions, we also don't have a way to then present them with the questions they skipped at the end. Going backwards would technically work but they would lose any data that they on that page they were currently on.

**Comment by AvivaOskow** [comment]
@LindsayYoung can you clarify your comment? Are you saying we can't make them clickable or we can't even show what the name of the pages are (which is different than we've had it all along)?

**Comment by LindsayYoung** [comment]
We can show the name of the steps. We can't click ahead.

How it works is that we have the following templates (pages) for the form:
    - Contact
    - Primary reason
    - Hate crimes and trafficking
    - Voting + location
    - Workplace + location
    - Police + location
    - Commercial/Public + location
    - Education + location
    - Location
    - Protected Class
    - Date
    - Details
    - Review page

Then we have logic based on primary issue and only show the relevant templates.
So, if you choose the police option as your primary reason, we will skip the unused template variants:
     - Voting + location
    - Workplace + location
    - Commercial/Public + location
    - Education + location
    - Location

So, if you are on contact and you click on the location step we don't know which template to give you because you haven't filled out the primary reason. 

As for clicking backwards, we know what template to show, but the user's session is saved when they hit the next button. So, if they are on details and they click to primary reason, any text that they entered won't be saved when they get back to the details page. 

Similarly, if you skip ahead and don't fill out the date we would have to make a way to force you back to the date page when you are trying to submit. But, that might be more easily solved than the other problems.

**Comment by LindsayYoung** [comment]
@AvivaOskow I think if the spacing between progress bar and box below is correct on dev? I think if it is we can close this ticket.
