### ISSUE TITLE
[Tech Task] Provide content for Spanish translation

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#436]
- [x] Check the portal for the latest and greatest copy edits
- [ ] Provide a document with the content from the portal to Marta and Laureen

**Comment by LindsayYoung** [comment]
Here is the file for translation:

[https://app.zenhub.com/files/183258764/f5a3ca55-4159-4aa3-b22d-83f8a2f38389/download](https://app.zenhub.com/files/183258764/f5a3ca55-4159-4aa3-b22d-83f8a2f38389/download)

I would like to verify with them that this format works for them. Also if they could use Notepad instead of Word for the translation, that would save us a lot of time.

**Comment by lalitha-jonnalagadda** [comment]
Thanks @LindsayYoung I will pass this to Marta and team. Anything in quotes in that file needs to be translated to Spanish. Correct?

**Comment by LindsayYoung** [comment]
Yes, for instructions:

The application looks at all  the words and phrases to be translated and creates this file. Using Notepad instead of Word, will save us a lot of time. (Word adds xml into the document that we would then need to strip out and we would probably have to reformat every quote mark.) The end result of the text is available on our[testing site](http://crt-portal-django-dev.app.cloud.gov/.) On that site, you can click though and create test submissions if you find it helpful for figuring out context.

**Document structure**

The document as about 19 lines of template at the top, that aren't required to be translated. Feel free to add any author information, but keep in mind, that information will then be public.

For each phrase, There will be a "#" followed by the source file and line number where it appears. You can ignore this reference, it will help us implement the translation later.

"msgid" is what text the system will Substitute out. This can be broken up into several lines. Don't worry about how those lines are quoted. You can treat each message as one whole piece of text to translate. 

Here is an example:

#: crt_portal/cts_forms/model_variables.py:16
msgid ""
"Store, restaurant, bar, hotel, place of worship, library, medical facility, "
"bank, courthouse, government buildings, public park or street, or online"
msgstr "Translation for the whole list will go here"


There are some HTM elements:
<strong>Bolded text will show up here</strong> (we use to show what part of the text should be bolded)

<a href="link destination">Link name to be translated</a> (we use this for hyper links to other pages, phone numbers or mailto links)

Happy to answer questions on tags if you have any.

Thank you!

**Comment by lalitha-jonnalagadda** [comment]
Emailed Laureen and Marta with the file. Future follow up on this will be via email, so this card can be closed.
