### ISSUE TITLE
Print form letter

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#475]
## Narrative

As an intake specialist, I would like to print form response letters so that I can send these responses via snail mail to the complainants

## Acceptance Criteria

1. Given that I'm on the form response pop up
When I click on the print button
Then I'm taken to the print options provided by my browser to print the form letter

2. Given that I'm on the form response pop-up
When I select the required form letter template from the drop down
AND
When I click the print button and finish printing a response letter
Then in the activity log of the complaint details page, I see the following log entry - **Printed "_Template name_"** (along with the username and the timestamp)

**Comment by blaughman** [comment]
@lalitha-jonnalagadda This looks good.

**Comment by blaughman** [comment]
@lalitha-jonnalagadda @cantsin @Jacklynn  Everything works great, but I have two concerns:  1) Should/can we remove the information highlighted in the printed form letter sample?  I'm okay with the date being on there.  2)  Would it be possible to tweak the margins a bit to make this one page?  It seems odd to have the second page only needed for two lines of the signature block.   Great work on a quick turnaround James[https://app.zenhub.com/files/183258764/7f6a2683-8718-4776-bf7b-601e52ffd042/download](https://app.zenhub.com/files/183258764/7f6a2683-8718-4776-bf7b-601e52ffd042/download).

**Comment by cantsin** [comment]
@blaughman ah, yes, I should have mentioned this before. The header and footer information is controlled by your chrome or system print dialog -- in Chrome it looks like this:

![2020-06-19_08-53](https://user-images.githubusercontent.com/3013175/85152834-52fdc000-b20a-11ea-9e16-9df97b466ed8.png)

I cannot turn these off since these are controlled by your browser/OS. So everyone who wants to use print has to turn these settings off. I realize this is awkward but this is really out of my control... (at least, as far as I'm aware)

As for tweaking margins, will see if I can fit everything in one page. Otherwise it may be easier to edit the template wording (coming soon!) to make the text fit in one page.

**Comment by blaughman** [comment]
Function works as intended.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/30.
