### ISSUE TITLE
Social Media requirements

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#533]
- [ ] Blurb for SEO 
- [ ] Image for Social media

### Blurb for SEO 
We uphold the civil and constitutional rights of all people in America

We need to add a meta description for the site. As a first pass we would want something we already have, so we can have a translation. We want something that has content that will have relevant keywords in it, like discrimination, voting, disability etc., since they are more likely to google for their specific problem than "civil rights" generally. It will also show in social medial so we need it to be coherent and represent what the site is. 

Proposal: 

- The Civil Rights Division upholds the civil and constitutional rights of all people in America. Civil rights laws can protect you from unlawful discrimination, harassment or abuse in a variety of settings like housing, the workplace, school, voting, businesses, healthcare, public spaces, and more.

### Add an image for social media
The seal would be fine if we don't have anything better.  We can always update this later if we get a better idea.  

Here is some research on image sizing for social medial https://blog.hootsuite.com/social-media-image-sizes-guide/

**Comment by Jacklynn** [comment]
I might make the blurb narrower to focus on complaint process instead of CRT, pulling from the landing page:
_Have you or someone you know experienced unlawful discrimination? The Civil Rights Division may be able to help. We enforce federal laws that protect you from discrimination based on your race, color, national origin, disability status, sex, religion, and familial status._

**Comment by Jacklynn** [comment]
Here are images, but I am guessing @AvivaOskow will want to tweak because she's updating the hero graphic too. It's a small and large. The facebook/linkedin big sizes seemed pretty much the same. Aviva has the sketch file too.

![Social-small.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/e646d061-083d-42c6-9458-a4fa6f6dda30)

![Social big.png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/695a525a-48cc-4b07-91e6-d040cc45cf8a)

**Comment by AvivaOskow** [comment]
Thanks for starting these @Jacklynn ! @lalitha-jonnalagadda I told Jacklynn already, but when I make the high-res image for the landing page I can button these up as well. I don't think we should need them before then anyway.

**Comment by lalitha-jonnalagadda** [comment]
If we get the hi-res image by EOD 5/27, we will use the high res image and if not, we will continue with the image above and replace with the next sprint.

**Comment by LindsayYoung** [comment]
@Jacklynn we should go for the last sentence because we do need the keywords for SEO

**Comment by Jkrzy** [comment]
Summarizing a bit,

We'll implement meta tags with consistent `Title`, `Description`, and `Image` across all external pages.

### Pages to include:
`Landing (/)`
`Report (/report)`
`Privacy Policy (/privacy-policy)`

### Title:
> Civil Rights Division - Department of Justice

### Description:
>Have you or someone you know experienced unlawful discrimination? The Civil Rights Division may be able to help. Civil rights laws can protect you from unlawful discrimination, harassment, or abuse in a variety of settings like housing, the workplace, school, voting, businesses, healthcare, public spaces, and more.

### Image:
TBD

**Comment by AvivaOskow** [comment]
@lalitha-jonnalagadda which social media platforms are we posting this on? Twitter, Linked in? Just want to get the proportions right

**Comment by AvivaOskow** [comment]
@lalitha-jonnalagadda Here are the updated images:

## **Facebook
![Facebook timeline](https://user-images.githubusercontent.com/21244661/83079727-7473ed80-a04a-11ea-88bd-183d62b1ff6b.png)


## Twitter**
![Twitter stream](https://user-images.githubusercontent.com/21244661/83079674-57d7b580-a04a-11ea-88c4-ee1d220f7464.png)

**Comment by Jacklynn** [comment]
looks good to me from when Joe pasted!
