### ISSUE TITLE
Test setting up division routing logic using Drupal Webform 

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#54]
## Narrative
As a DOJ intake specialist, I want to make sure that a complaint is routed to the correct division. 

## Notes
~Investigating the Maestro module to see how we'd set up routing logic in Maestro.~ 
Investigating the Webform module to see how we'd set up routing logic

**Comment by UchMok** [comment]
@LindsayYoung and I worked on this today testing routing logic on the webform module. We think we need an additional plug in called 'webform conditional' in order to add the routing use cases. Adding this plug in is dependent on 
- restaging cloud.gov
- getting acquia hosted site set up

**Comment by UchMok** [comment]
@LindsayYoung were we able to add 'Webform Conditional'?

**Comment by LindsayYoung** [comment]
I got a moment this morning to look at this.

Composer isn't recognizing webform conditional and it is not installing it. I am going to try that for a bit longer and then I am going to look at handlers.

Here is a handler code for future reference: 
https://www.drupal.org/docs/8/modules/webform/webform-cookbook/how-to-programmatically-add-a-handler-to-a-new-webform

**Comment by LindsayYoung** [comment]
Ok, the webform rules might be helpful https://www.drupal.org/project/rules_webform

**Comment by LindsayYoung** [comment]
Ok, it doesn't look like we need a plugin it looks like we can make custom computed elements. 

I tested this locally and it worked. I created a twig template computed element that was not visible but saved in the database.

    {% if data.primary_complaint == 'Ability to vote was impacted' %}
        {{ 'voting' }}
      {% else %}
        {{ 'not voting' }}
    {% endif %}

I tried adding Jacklyn's form since I wanted to use that as a base and things got out of sync so I will get a PR together as soon as I get my local straightened out.
