### ISSUE TITLE
Figure out how to access Acquia-hosted Drupal site as admin

### ISSUE THREAD

**Issue by alexsoble** [18F/crt-portal#55]
## Narrative
As a developer, I want to log in to my Acquia-hosted Drupal site as an admin, so that I can manually enable plugins and drop in content files if needed.

**Comment by LindsayYoung** [comment]
I am going to close this issue in favor of https://github.com/18F/crt-portal/issues/21 

That issue has a list of the accounts to make on staging and we should be clear that we don't want to enable modules by hand in the cloud-based admin interface because that creates configuration and code that doesn't make it into source control. Also, it can cause a bad error in the app.
