### ISSUE TITLE
Landing page copy edits for Sprint 20 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/crt-portal#550]
## Content
- [ ] This card will capture all the 'must have' copy edits we need to incorporate into sprint 20 as they were left over from 6/4 launch build. Changes can be found here: **Highlighted in green & blue** https://docs.google.com/spreadsheets/d/1ZX-IKH6_uJQLEq20G33Yva3RwC8PZccKR1fkS9r8BJw/edit#gid=1416703596 

-- here's our [working document](https://docs.google.com/document/d/1xZ6EnZv25AygfUQbhBC2ClLFkZ0qK9FshdIp85w5Wuw/edit?ts=5ecef13f)t which I think is a little easier to read but I don't want to cause confusion

## Text changes blocked out
![civilrights.justice.gov_(iPad Pro).png](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/1b048cd7-6cac-4bdc-82fc-ed1c191044e2)

**Comment by danielhyi** [comment]
Added some copy edits!

**Comment by Jkrzy** [comment]
Thanks friends! I implemented all of the changes from the spreadsheet highlighted in green.

https://github.com/usdoj-crt/crt-portal/pull/537

This part feels a bit wonky since it overlays a portion of the background with a-lot of action. I'm not sure how to replicate the mock with just CSS, maybe @hbillings has an idea?
![Screen Shot 2020-06-10 at 11.20.17 PM.png](https://images.zenhubusercontent.com/5e55861e4853ae9aab609188/9af8a880-98ad-4381-9599-a74b19ce67e6)

**Comment by blaughman** [comment]
Landing page reflects all of the changes.  Moving to UAT.

**Comment by lalitha-jonnalagadda** [comment]
Deployed on 6/16
