### ISSUE TITLE
Spanish versions for existing form letters

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#670]
## Narrative

As a CRT Intake Specialist, I need Spanish versions of form letter responses so that I can respond to complaints presented in Spanish.

**Comment by blaughman** [comment]
Spanish versions of the response letters added to the source of truth for form letters.

https://docs.google.com/document/d/1pR3_t8jDXHgdCD1YMWkmykCH43y7A4aPc32s7-BNKPw/edit#heading=h.5vshnciuxwma

**Comment by cantsin** [comment]
@Jkrzy thinking about this one from an architectural standpoint. 

As far as I know, Django doesn't really have a "canonical" way of doing i18n for dynamic content (database models) -- the best library I can see is [django-modeltranslation](https://django-modeltranslation.readthedocs.io/en/latest/). This library modifies the underlying fields with an additional `_{lang}` per language, which is ... ehhh. I can live with that. Unfortunately this library assumes that users are setting the language cookie, which is not what we want here -- we want to maintain the `en` language cookie for users, all the while providing language variants of a model. Are you aware of any better libraries or approaches?

Otherwise I think it may be simpler to add the spanish form letters as-is and explicitly mark them as, say, `CRT - No Capacity (Spanish)`. In other words, the spanish letters would just be a series of `ResponseTemplate`s. This way is not as nice as building in full featured i18n support for form letters, admittedly, but I'm also a bit wary of over engineering here.

Thoughts?

**Comment by Jkrzy** [comment]
Adding them as `ResponseTemplates` instances is appropriate with the current state of Form letters,

Beyond our current implementation, I'd _love_ to look at migrating form letters out of the database and into the code repository

**Comment by cantsin** [comment]
Alright, thanks for the feedback! I'll take this one on then.

@blaughman is it OK if we have the spanish versions as fully standalone letters? These will be distinguished with a `(Spanish)` at the end of the title.

**Comment by cantsin** [comment]
@blaughman also do we have the spanish translation for `Response: Your Civil Rights Division Report - [record_locator] from [section_name]`? Apologies if it's here somewhere, but I couldn't find it.

**Comment by blaughman** [comment]
@cantsin Fully standalone letters would be perfect.  I'll check with Marta about the last translation question.

**Comment by cantsin** [comment]
@blaughman thank you!! One additional thing to ask Marta too, please ask how she wants her dates formatted. Here's an example:

`01 septiembre 2020` -- not sure if I should be adding commas anywhere or adjusting this format. My spanish teacher in high school is shaking his head at me right now ...

**Comment by cantsin** [comment]
After researching some more, I believe the best alternative is to use an external library. This library will translate today's date as `1 de septiembre de 2020` which seems correct to me. (But still best to double check with Marta)

**Comment by cantsin** [comment]
While finishing this feature up, I realized we are missing one more thing. Section names. We updated the section names awhile ago and I believe some Spanish translations need to be updated as well.

Here's the list I have (I've marked which ones I know for sure we need to update, but let's check all with Marta):

Administrative: Administrativa
Appellate: Apelación
Criminal: Penal
Disability Rights: Discapacidad (needs to be changed)
Employment Litigation: Servicios de Litigios Laborales (needs to be changed)
Educational Opportunities: ??? (I don't think we ever had this phrase translated)
Federal Coordination and Compliance: Coordinación y Cumplimiento Federal
Housing and Civil Enforcement: Vivienda (needs to be changed)
Immigrant and Employee Rights: Derechos de Inmigrantes y Empleados
Special Litigation: Litigios Especiales
Voting: Votación

Also, since we are adding `Section` to the actual section name, I believe we should account for this as well. For instance, `Voting Section` is probably `Sección de votación` if Google Translate hasn't led me astray.

**Comment by cantsin** [comment]
I just remembered! Hope it is not too late :sweat_smile: We need spanish translations for the "Thank you for your report" case when the user does not input their first or last name. (Otherwise it will be `Estimado/a [first_name]` or `Estimado/a [first_name] [last_name]`

**Comment by ilodidoj** [comment]
@blaughman @randyabramson no spanish version for FBI letter and trending letter needed for this AC right? Did not see those during PR review or in the card here.

**Comment by blaughman** [comment]
Spanish form letters appear to work as intended.  Moving to UAT.
