### ISSUE TITLE
Assignee filter not working on Prod in EDGE

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#676]
### Issue
We were contacted on the evening of 8/21/20 by Ayanna Brown. She was using the portal admin on PROD in EDGE and noticed that the assignee filter was not populating in the filter list when she tried to filter on the 'assignee' name 'mgarcia,.' (screen grabs below)

![magarcia-fill-in-edge.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/0ea8db13-5ef3-471e-9c8f-c11d912a3d58)

![magarcia-no-filter-surfacing-edge.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/93cb2da1-7058-4a63-bde8-27a8ada45fd9)

@randyabramson  started to troubleshoot and noticed that the portal and assignee filter was working as expected in CHROME.

@randyabramson then told Ayanna to try to filter on 'mgarcia' in CHROME. She did and the filter worked as expected. She then went back to EDGE and tried to once again filter on 'magarcia' and the filter worked as expected.

@randyabramson recreated all of the steps above on his PC laptop and saw the same results on the PROD url: https://crt-portal-django-prod.app.cloud.gov/form/view/?status=new&status=open&no_status=false.

### Other observations

1. @randyabramson  tried to clear his history on EDGE to see if it made a difference. It did not
My 'clear history' selections are here:

![clear-history.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/0417ea08-e5c9-445e-a1b2-00370c53df65)

2. @randyabramson noticed that additional assignee filter searchers in EDGE (example: rberman) after the initial search for 'mgarcia' on Chrome did not yield successful filtered results.

3. @randyabramson noticed that after successfully seeing filter results for 'mgarcia' in EDGE (after filtering for this result first in CHROME), he was not able to successfully filter on 'mgarcia' after several opens/closes of EDGE.

**Comment by randyabramson** [comment]
Closing ticket 580

**Comment by cantsin** [comment]
So what do we want to do here, exactly? The bug is in the underlying [library](https://github.com/alphagov/accessible-autocomplete) which is *not* accepting pull requests at the moment. 

The only solution I have here is to disable this library outright if we know the user is on Edge. Other than that I'm open to suggestions...

**Comment by randyabramson** [comment]
@cantsin - what would the experience be for the user if we disabled the library?

**Comment by cantsin** [comment]
If we disable this library for Edge users, then the user must select the assignee from a (possibly long) list of users. In other words, the user will lose the ability to quickly filter the user list. 

![2020-08-31_09-19](https://user-images.githubusercontent.com/3013175/91742406-16840400-eb6b-11ea-846a-a1a0db5aefd9.png)

**Comment by randyabramson** [comment]
@cantsin OK, I understand. I assume that this build will eventually fall out of use as new browser updates happen and are installed by our IT group, correct?

**Comment by cantsin** [comment]
I'm not sure! Earlier Edge builds worked, while later ones did not. Do we know when the next round of browser updates are slated to happen? If this isn't fixed by then then I think we should either remove the library or replace it with something else.

**Comment by ilodidoj** [comment]
There is no specific date set for browser update for all remote users.  Only next new image for user may have the latest EDGE browser.   Even with this I feel workaround is much more UI friendly than removing the library.  Currently on EDGE if the user type can see a short list and can then type the intended assignee from there without picking from the list, aka workaround. Note it's only 8 character max due to the login id it's mostly first initial and last name up to 8 character long or less.  Not a huge burden on users compare to select from a long list as alternate when library is disabled.

**Comment by randyabramson** [comment]
Very good point, @ilodidoj
