### ISSUE TITLE
Complaint Form Copy Edits

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#687]
Randy identified some minor copy edits to make on the complaint form.

Remove the semicolons on the personal description page:
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/49a9f853-6ef7-4647-b00d-a00f3b8a5773)

Remove the word "and" at the end of the second bullet point (highlighted in the screen capture)
![image.png](https://images.zenhubusercontent.com/5d2390b2c408a2441fc2874d/675c67f6-a288-41bf-89da-6bfc29e96de1)

**Comment by ilodidoj** [comment]
@randyabramson @blaughman while we are removing (;) should we also remove the (.) at the last line? or should add period (.) for all three lines? just to be consistent.

**Comment by randyabramson** [comment]
@ilodidoj thanks for picking this up. The rule is that periods should be on each bullet if the words compose a sentence, which these do. This is a bit more complicated because the bullets start with a lower case letter on the first word, so it is hard to see these as sentences. Anyway, looking at these again, I think we should make the first letter a capital in each sentence and add periods at the end so they read:

* A court, magistrate, or administrative tribunal, including disclosures to opposing counsel in the course of settlement negotiations.

* A Member of Congress submitting a request involving an individual, to whom the record pertains, when the individual has requested assistance from the Member with respect to the subject matter of the record.

* A contractor with the Department of Justice who needs access to the information in order to perform a contract. Recipients of information shall be required to comply with the requirements of the Privacy Act of 1974, as amended, pursuant to 5 U.S.C. 552a(m).

* A Federal, State, or local law enforcement agency, if we become aware of a violation or potential violation of law or regulation outside the scope of our jurisdiction.

**Comment by hakhalid11** [comment]
@randyabramson are the bullet points in your comment pertaining to personal description page?

**Comment by randyabramson** [comment]
@hakhalid11  yes, you are correct:

![image.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/7cbc1c92-bd18-4f44-87f3-38b425b69be8)

**Comment by hakhalid11** [comment]
@randyabramson So I am assuming we would want a period after each bullet point?

**Comment by randyabramson** [comment]
@hakhalid11 - actually remove the periods.  

So, it should read:

* Time
* Names of people involved including witnesses if there are any
* Any supporting materials (please list and describe them)

@ilodidoj and @hakhalid11  I think I confused this ticket with punctuation on a separate page, hence the block of text above that is not on the personal description page.  I will enter a separate ticket for that one. Sorry about that!

**Comment by blaughman** [comment]
Edits appear to have been incorporated.  Moving to UAT.
