### ISSUE TITLE
ValueError in `ShowView.get`

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#702]
We've seen ~280 occurrences of the following exception, peaking during business hours, since the latest release on Tuesday.

```
builtins:ValueError
/cts_forms.views:ShowView.get
invalid literal for int() with base 10: ''
```
Caused by an empty string being stored in `index` when this line, https://github.com/usdoj-crt/crt-portal/blob/1ddda91256f540f5515a687d4a09a419996c4518/crt_portal/cts_forms/views.py#L196, is executed.

Originating the from report details page, `/form/view/{ID}`

Initial suspicion is this is unexpected behavior in the new report navigation functionality added in https://github.com/usdoj-crt/crt-portal/pull/635

**Comment by Jkrzy** [comment]
~140 additional occurrences in the last 24 hours.

cc: @randyabramson, @blaughman, @ilodidoj

**Comment by randyabramson** [comment]
@Jkrzy  can you give more detail of when/where this error occurs? I believe this is different from the bug on our internal view when the specialist click into the Summary field and then leave it blank, correct?

**Comment by Jkrzy** [comment]
@ilodidoj is on the right path but this is just the initial report. 

@randyabramson, @ilodidoj, and @blaughman should:
* Triage and set a priority for this card
* Including whether or not we should tackle as a hot-fix
* If the priority supersedes other in-development work, assign it to a developer for investigation and resolution

**Comment by randyabramson** [comment]
@Jkrzy @ilodidoj I could not recreate this error.

I _could_ send a note to the deep dive group and see if anyone has gotten an error when using the <> buttons. Would that be helpful?

**Comment by randyabramson** [comment]
@ilodidoj @Jkrzy @blaughman 

Here is the evaluation from Tony Burton who got this error:

_"What I’ve been getting, for the past three days, is a message screen (below) whenever I save my work to the entry (ticket). Yet when I go back to the entry, the update has been made, and the success is noted at the top. It’s not just germane to this one entry, it happens every time. I’ve haven’t said anything before now because 1) I thought it was a temporary bug you all were working out, and 2) that, of all the people who use the portal, somebody else would. So now you know. It’s a pain, but it does do what it’s supposed to, so…
Hope you guys can work this out. It’s not stopping my work, but it really ought to be attended to. Thanks for checking with me.
Tony"_

Answers to questions I posed:

What browser are you using? : MS Edge
Do you recall what fields you might have interacted with? : Reported Complaint, Action and Activity
Did you use the back/forward buttons at the top? The Print function? Any other buttons? : The back button at the top. No other buttons (print, etc.)
What did the error look like? : See below

![DOJ-error-page-500-error.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/e1b96561-ab3c-45e9-a420-a3106df9bf2a)

Answers to questions I posed

**Comment by randyabramson** [comment]
@ilodidoj  @Jkrzy  @blaughman 

I think Tony might be the only person impacted at the moment, so I don't think this is a DEFCON 1 situation just yet.

We did get  a note from Sharon  McGowan-Bransome who is getting a 500 error as well, but I need to confirm that she used the 'back' navigation.

I will move this up in priority and ask the Deep Dive group if others are seeing a 500 error.

Randy

**Comment by randyabramson** [comment]
Update to Tony's issue description - the error occurred when he hit the 'back button on the browser.' (not the back to all or complaint-level navigation (forward/back)).

![image.png](https://images.zenhubusercontent.com/5ef156d51dd4f26e61414bbf/72ad2547-d81c-40a1-b467-5d47a42cade5)
