### ISSUE TITLE
[design] text weight increase on rollover 

### ISSUE THREAD

**Issue by Jacklynn** [18F/crt-portal#732]
On the landing page it looks like the text weight changes when you click on the primary issues drop down, by default it's heavier weight than when the drop down is showing. I would expect it to be the thinner weight always. 

![Text weight bug.mov.gif](https://images.zenhubusercontent.com/5d1a3b0bcc794602e102a513/751ef198-8c51-487e-b151-29880323c074)

**Comment by kmanubhai** [comment]
Hey, I was notable to replicate this issue, also on the code side i do not see font weight being changed on clicks. I am thinking this might be browser related, maybe even specific version of update. I checked this on Chrome Version 86.0.4240.75 (Official Build) (64-bit) GIF is below, did test on IE11 and Firefox but I primarily use Chrome.

If you are still experiencing this bug please provide me the browser and version information. - Thanks

![732-chrome-test.gif](https://images.zenhubusercontent.com/5f7f4613b2a3817d8f81f1ed/068e560c-517b-48e1-90a8-51bdd44f6450)

**Comment by randyabramson** [comment]
Hey @Jacklynn -- we can't recreate this in CHROME or EDGE or on iPhone Safari.

Can you share your browser version with us?

Thanks!

**Comment by Jacklynn** [comment]
I'm using Chrome, the weight doesn't change until you click on it though (like to close or open it)

**Comment by timoballard** [comment]
@ilodidoj and I looked into this issue this morning. We're able to replicate only on Mac OS, using both Chrome and Safari. The visual change is triggered by the property `-webkit-font-smoothing`, which is set to `subpixel-antialiased` when the button is inactive, and `antialiased` when the button is active. We're guessing that this problem is specific to Mac fonts, since we see it in all browsers on Mac OS, but nowhere else.

**Comment by timoballard** [comment]
@ilodidoj @blaughman @randyabramson - I think we can close this as `not doing`

**Comment by randyabramson** [comment]
I will close it, @timoballard
