### ISSUE TITLE
Inventory list of current 'work arounds'

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#781]

**Comment by cantsin** [comment]
Anything y'all need help with here, from the dev side?

**Comment by randyabramson** [comment]
Hi @cantsin yeah! We are really just looking for a list of outstanding workarounds that are out there (example: You have to spell out the full name on EDGE).

Once we have a list, we can start prioritizing these.

TBH, I am not aware of that many workarounds.

**Comment by cantsin** [comment]
Currently (with the older accessible-autocomplete library) we had a workaround for changing assigned users in Edge: select the user, click outside the select, then re-select the user. Basically we had to re-jigger the autocomplete until it kicked in. We have a new library now, though, which should fix this particular workaround.

One possible workaround that may still remain: unselecting the assigned user (iow, setting no assigned user) is still a bit fiddly at present, even with the newer library (this is an inherent limitation due to how these "wrappers" work). More testing is needed.

Other than these, I'm not aware of any user workarounds; the assigned user bug is by far the most annoying afaik.

**Comment by randyabramson** [comment]
Thanks @cantsin for the above. CC'ing @blaughman. If we can't think of others, we can close this out.
