### ISSUE TITLE
Django-compressor, remove if we're not going to use it

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#792]
In https://github.com/usdoj-crt/crt-portal/pull/747 and #562 we re-evaluated our implementation of `django-compressor`. On initial review it looks like it may not be necessary.

We'll continue that investigation and resolution here. 

> Definitely reasonable. django-compressor feels like its not necessary here; maybe we can remove outright, since we already use gulp to copy the js files -- maybe we can go ahead and bundle them up instead there (in gulpfile.js). Will do a bit of investigation. 

## We'll know we're done when
- [ ] We've made a decision as to keeping or removing django-compressor
   - [ ] If keeping, we've identified and implemented a minimal beneficial implementation
- [ ] If removed and an alternative is identified, we've implemented if

cc: @cantsin

**Comment by cantsin** [comment]
Update:

Bundling javascript assets via gulp will bundle _all_ our javascript files together, which isn't quite what we want. For instance, loading the front page will load javascript for the backend (and quite possibly break IE11 besides, since our backend javascript code isn't vanilla anymore). 

I'm experimenting with making a distinction between backend and public javascript bundles. The tricky part is overlap, such as modal javascript code. Open to other suggestions if anyone has them.

**Comment by Jkrzy** [comment]
Is there's another valuable, and hopefully tiny 😅,  interim step we can take to add hashes and/or otherwise do some cache breaking when we push new versions out. To avoid the "did you do a hard refresh?" dance.

**Comment by cantsin** [comment]
Yes. There's `gulp-fingerprint` if we go all in with gulp -- fingerprinting in general, though, may be a different issue. Note that django-compress doesn't support fingerprinting either. That aside, I'm not aware of any good Django libraries for such, did you have any recommendations?

**Comment by Jkrzy** [comment]
I think we can hook into `django-storages` with [ManifestFilesMixin](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#manifestfilesmixin) though it looks a few folks have had trouble recently and needed a work-around:
https://github.com/jschneier/django-storages/issues/841

**Comment by cantsin** [comment]
@Jkrzy it does look like `ManifestFilesMixin` will do what we want but I consider fingerprinting to be orthogonal to the issue of removing (or keeping!) django-compressor. Should we have a separate PR for fingerprinting?

**Comment by cantsin** [comment]
Played around with `ManifestFilesMixin` a bit, I _think_ this will do what we want (but needs more testing)

```diff
diff --git a/crt_portal/crt_portal/settings.py b/crt_portal/crt_portal/settings.py
index 2fa3e695..7561b4ea 100644
--- a/crt_portal/crt_portal/settings.py
+++ b/crt_portal/crt_portal/settings.py
@@ -16,6 +16,9 @@ import os
 import boto3
 from django.utils.log import DEFAULT_LOGGING
 from django.utils.translation import gettext_lazy as _
+from django.contrib.staticfiles.storage import ManifestFilesMixin
+
+from storages.backends.s3boto3 import S3Boto3Storage

 # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
 BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
@@ -226,6 +229,17 @@ if environment == 'PRODUCTION':

 STATIC_URL = '/static/'

+class ManifestS3FilesStorage(ManifestFilesMixin, S3Boto3Storage):
+    def read_manifest(self):
+        """
+        Work around a bug where S3Boto3Storage throws IOError but
+        ManifestFilesMixin expects FileNotFound.
+        """
+        try:
+            return super(ManifestS3FilesStorage, self).read_manifest()
+        except IOError:
+            return None
+
 if environment not in ['LOCAL', 'UNDEFINED']:
     for service in vcap['s3']:
         if service['instance_name'] == 'crt-s3':
@@ -245,7 +259,7 @@ if environment not in ['LOCAL', 'UNDEFINED']:
     AWS_LOCATION = 'static'
     AWS_QUERYSTRING_AUTH = False
     STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
-    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
+    STATICFILES_STORAGE = 'ManifestS3FilesStorage'
     DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
     AWS_DEFAULT_ACL = 'public-read'
     AWS_IS_GZIPPED = True
```

**Comment by cantsin** [comment]
OK. So I think we should keep django-compressor after all (and use it for js bundling).

Unfortunately, when doing bundling via gulp, I found out that most of our javascript files assume that certain elements are present when running said script. If I naively bundle all the public javascript scripts, for instance, we get a ton of `getElementById` errors because the ids referenced on certain forms are not present on the front page. We can rewrite the javascript (which I am loathe to do, but it is possible), or else bundle them up as listed in the templates (which means bundling would have to happen on the django template layer, hence django-compressor). 

Technically speaking, the only thing we need gulp for is to build the SCSS packages (and re-build SCSS) -- the `init` gulp command does not seem needed anymore. But we still need a way to watch and rebuild SCSS, so we may be stuck with both gulp and django-compressor after all,.
