### ISSUE TITLE
Frequent Flyer - View All Table

### ISSUE THREAD

**Issue by blaughman** [18F/crt-portal#819]
## Narrative
As a CRT user, I want to see if there are multiple records associated with an email address so that I know the complainant is a potential frequent flyer.

## Acceptance Criteria
1) Given I am on the view all table
when I look between the 'Status' column and the 'Routed' column
then I see a column labeled 'Total #' with a sort arrow on the right

2) Given I am on the view all table
when I see a value in the 'Total #' column
then I know the email address in that row has more than one record in the system
AND 
I see the value of the number of associated records listed in the 'Total #' column

3) Given I am on the view all table
when I click on a value in the 'Total #' column
then I am taken to the complaint detail page for that particular record

## Assumptions
- should include existing record (always has to be 1 or above)
- clicking the sort arrow again will sort the data in ascending order

## Technical Questions / Future Functionality
3)  Given I am on the view all table
when I click the sort arrow in the 'Total #' column
the data is sorted so the email address with the most associated records is listed first 
AND
the other records are sorted in a descending order

**Comment by emilycryan** [comment]
Here is the link to the prototype (inter-connected wireframes)

https://invis.io/ARZOW23Z3YP

Notes:
- Table view functions as normal with "Total #" being sortable by same rules as the other columns
- When a user clicks into a record, "Back to all" retains filters from the previous filter set
- If a user clicks "View all (x)" on the individual record view, they should return to the table view however, all filters should be reset so that the only filter applied is the email address. New, Open and Closed records matching the email should all show (*)
- The "Letter Sent" link should only be implemented once we have email working; otherwise we will not know if a complainant was emailed. 

(*) I'll defer to @blaughman @randyabramson @AvivaOskow on the general USDS rules around showing all / none in terms of the checkboxes that correspond to Open, Closed, New. All checked == all unchecked so not sure what our general rule of thumb is here for which of those two options are utilized in this sort of situation.

**Comment by emilycryan** [comment]
@timoballard We have come to a decision. This was what I put forth toe Randy and Bill:

- Using a "0" would cause a slew of records to show 0 but technically that's not accurate. It's not that there are 0 records by a particular user, it's that we don't know what their email actually is to count it.
- Adding up all the ones with blanks would cause an abnormally high number, like "8,389" which then groups them all together and again misrepresents the accurate count similar to showing "0" It also would require grouping together on the individual view which would also be inaccurate.
**- The best option would be a "N/A" or "--" to be used. One, it shows the record is not being "counted" because it shouldn't be. Two, it shows that at the moment that we don't know if this is a duplicate or not. Finally, if it's non-numeric, we could force sort to always push that to the end of the results, showing up only on the last pages of records, regardless of whether we are sorting ASC or DESC which would prevent it from throwing the results off in the table view. It basically is a deprioritized grouping which is what we wanted to do with records w/o emails and phone numbers.**

We can discuss the sort but the idea is to ultimately deprioritize the records w/o emails - a forced sort would/could do that. To be discussed at the 3:30 mtg. 

CC @randyabramson @blaughman

**Comment by Jkrzy** [comment]
@timoballard, if we dropped sorting from the implementation here can you let us know so @blaughman or @randyabramson can create a new card for it?

**Comment by timoballard** [comment]
Yes, this implementation does not include sorting, so we will need a new card to capture that work @blaughman @randyabramson

**Comment by randyabramson** [comment]
Got it @timoballard and @Jkrzy 

This is still a huge win. Thank you for the speedy and excellent work!

**Comment by blaughman** [comment]
@Jkrzy @timoballard @randyabramson Card 843 has been created.  Please feel free to drop comments in the card.

**Comment by blaughman** [comment]
Function works as intended in Chrome and Edge.  Moving to UAT.

**Comment by randyabramson** [comment]
Worked as intended on Edge and Chrome on Staging

**Comment by blaughman** [comment]
Function confirmed in staging prior to production release.
