### ISSUE TITLE
Analytics on staging environment

### ISSUE THREAD

**Issue by Jkrzy** [18F/crt-portal#837]
Building on [#788](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/788), as a developer I want our analytics in staging to mirror production  analytics in staging environment, giving us the ability to test implementation in a non-production environment.

### We'll know we're done when
- [x] Google analytics suite is implemented on staging (Google Tag Manger and Google Analytics)
  - [x] Profiles, views, or other approaches to isolate staging data from production
- [x] DAP is implemented on staging
- [x] Touchpoints is implemented on staging

**Comment by timoballard** [comment]
@randyabramson - reminder to send me a GA invite when you have a moment, thanks!

**Comment by randyabramson** [comment]
@timoballard - just assigned you in GA. Let me know if you don't get the invite.

**Comment by timoballard** [comment]
@randyabramson - [PR open](https://github.com/usdoj-crt/crt-portal/pull/799) for these changes. I adjusted things on the GA side so that there are separate Views for Production and Staging. Let me know if you want to grab some time to run through the changes (although the Staging View will be quiet until the next deploy, obviously).

**Comment by randyabramson** [comment]
Activity is counted on staging. Moving to UAT complete.
