### ISSUE TITLE
Research protocol/needs for user testing

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#852]

**Comment by emilycryan** [comment]
Research protocol (in-progress)
Link: https://docs.google.com/document/d/1Z1TeCrIoiaP7neyZNmcddnvHR6MFJe4BYvKZ4Y3rgLo/edit?usp=sharing

Outstanding questions / needs:

We want to utilize two separate efforts:
1. Previous Reporter: Someone who recently submitted a report to us and has volunteered to chat over the phone for followup questions on their experience. Requirements: Phone
2. Simulated Experience: Someone who is given a scenario and then asked to do tasks related to that scenario on their computer. Requirements: Phone and computer

Questions:
What do we need to do to get folks for scenario #1 (Previous Reporter)?

- Popup/modal on submission
- Contact info (phone only)

What do we need to do to get folks for scenario #2 (Simulated Experience)?

- How can we find ppl? How was this done in previous research efforts?
- Do we offer any incentives? Guessing “no” but making sure
- How can we get the hard to reach folks
    - Disabled
    - Elderly
    - Those w/o computer access

**Comment by randyabramson** [comment]
Great start on this, Emily!

I put some notes in the doc. Also, if you don’t get answers from Jacklynn, perhaps we can check with other agencies on how they might have handled this sort of work.

Randy

**Comment by emilycryan** [comment]
FYI @randyabramson I did some digging around the PRA Dan mentioned yesterday and we do have the ability to do user research that is specifically exempted from PRA requirements. It's documented here: https://obamawhitehouse.archives.gov/sites/default/files/omb/inforeg/memos/2014/appendix-data-search-tools-calculators.pdf

Under 5 C.F.R. 1320.3(h)(3), the manner in which we research is exempt specifically because we are gathering "Facts or opinions obtained through direct observation by an employee or agent of the sponsoring agency or through non-standardized oral communication in connection with such direct observations"

I can continue to check with others but I imagine we are covered under this statute exemption even though Lindsey and Jacklynn stayed under the threshold of 9 users (which, I would like to get more than 9 following this protocol in both buckets)

As a reference this article was solid and pointed me in this direction (https://eriemeyer.medium.com/user-research-is-not-illegal-uncle-sam-51f2f92a280a)

CC @AvivaOskow @blaughman

**Comment by randyabramson** [comment]
@emilycryan Amazing sleuthing! Thanks so much for this extra effort! Very excited to get this research!

**Comment by randyabramson** [comment]
@emilycryan once we're close to being ready, we should connect with Killian just to make sure he's on board with the plan.

**Comment by emilycryan** [comment]
Notes for research:

FEC solicits feedback from users via "Feedback" popup (bottom right corner): https://www.fec.gov/

* my one concern is that we already have low engagement on the feedback popup. We should consider something more obvious *

This is the form to signup: https://ethn.io/12085

We should be covered under GSA's PRA:
GSA has a “Generic Clearance for the Collection of Qualitative Feedback on Agency Service Delivery” that you should be able to use.

* 		OMB CONTROL NUMBER: 3090-0297
* 		EXPIRATION DATE: 08/31/2022	
* 		ICR REFERENCE NUMBER: 201907-3090-009

Terms of Clearance: OMB approves this collection for a period of 3 years. To request approval of information collections under this generic approval, GSA must do the following: 1) Unless GSA is using multiple modes of collection (e.g. paper forms and electronic submissions), provide a Generic Clearance Submission Template for each instrument; 2) If GSA is using multiple modes of collection (e.g. paper forms and electronic submissions), the same Generic Clearance Submission Template may be used for both instruments; 3) each Generic Clearance Submission Template must be uploaded as a Supplementary document using a naming convention allowing the public to identify the associated instrument; 4) submit no more than five Generic Submission Templates with each request.

I believe these are examples of this clearance submission template but will need to find out for sure:

https://www.reginfo.gov/public/do/PRAViewICR?ref_nbr=201907-3090-009
https://www.reginfo.gov/public/do/PRAViewIC?ref_nbr=201907-3090-009&icID=240651

CC @randyabramson @blaughman

**Comment by randyabramson** [comment]
@emilycryan - regarding the solicitation form, I agree that the simple tabs at the bottom of the pages are not effective. We can create any modal or hard coded button we want and then link to the input form on the Touchpoints site. 

Regarding clearance, are we covered by https://obamawhitehouse.archives.gov/sites/default/files/omb/inforeg/memos/2014/appendix-data-search-tools-calculators.pdf?  If so, how does the OMB clearance tie in? Do we need to clear both hurdles?

**Comment by emilycryan** [comment]
@randyabramson I'll work with @AvivaOskow on some options for the modal / popup and we can take a look at them. As for the clearance... it's not a blanket cover for us. We still have to be beholden to the PRA reqs. I can share more tomorrow - Jacklynn and I chatted this evening. Regardless, we should be OK to work through this but we will need Dan or Kilian's final "OK" after we present the paperwork and plan. I've got to get some notes together and next steps which I'll do tomm. 

CC @blaughman

**Comment by randyabramson** [comment]
Got it....thanks @emilycryan

**Comment by emilycryan** [comment]
Updates as of Jan 29:

- We need our own PRA. We should do what GSA did, if possible, and get a blanket, 3 year one, to cover any research efforts (justice, ada, art, etc) and we should maintain/renew it just as GSA does.
- - We need our own usertesting.com account bc we cannot use the GSA one with our own PRA. 
-     - GSA goes through ForumOne bc usertesting.com isn’t fedramped.
-     - We will need our own contract with ForumOne (forumone.com) since we cannot piggyback on the GSA one.
- - We can use the panel in usertesting.com to run any/all test (including the ones we solicit from actual site users) in order to organize and incentivize participants.
- - We should look to other agencies (HUD, EEOC, etc) to recruit participants who may not be part of usertesting.com’s test participant bank. This would also give us more access to individuals who more closely align with our user base.

NEXT STEPS:
- PRA for testing
- Research Privacy Policy (in-progress)
- ForumOne/Usertesting.com account/contract

As a reminder, this is the GSA PRA template:
https://www.reginfo.gov/public/do/PRAViewICR?ref_nbr=201907-3090-009
https://www.reginfo.gov/public/do/PRAViewIC?ref_nbr=201907-3090-009&icID=240651

CC @randyabramson @blaughman

**Comment by emilycryan** [comment]
Feb 1:
Privacy Act Update:
https://docs.google.com/document/d/12mdhUpDwAOzUA6Cm_i6h2LsfxiJGEeNwM4tsyzO-7dI/edit?usp=sharing
(edited/new content in red)

CRT Visitor Research Privacy Policy (New):
https://docs.google.com/document/d/1b1VLIJ9grkMF8P0Hw1Fiw--RkNU73LJhO7rz1-gqCmg/edit?usp=sharing

**Comment by emilycryan** [comment]
Issue is blocked due to pause in PRA needs
