### ISSUE TITLE
Mock for language filters on back end

### ISSUE THREAD

**Issue by randyabramson** [18F/crt-portal#918]
@emilycryan @AvivaOskow 

Can you please work up a mock for how intake specialists would filter on reports in different languages on the view all table?

@timoballard mentioned filtering would be possible, but we would not be able to track users who came in to the Portal by changing the language in their browser setting.

Note that the languages we'd filter on are:

Chinese Simplified
Chinese Traditional
English
Korean
Spanish
Tagalog
Vietnamese

**Comment by emilycryan** [comment]
Here's the quick and dirty mockup. Some notes.
1. The filter should live under "MORE" but should always be defaulted to English. That is, the user shouldn't have to set it whenever they come into the site. As such, the tile should also be present telling them it's set to English, even if they havent' opened. 

2. The user should be able to change it and it should be a single selector like Classification bc we don't want users to select two or more languages at once in order to minimize accidentally sending the wrong translations. The assumption is the user will be working in a "language mode" and will only be focused on one language at a time. 

CC @randyabramson @blaughman @AvivaOskow 

![Screen Shot 2021-04-06 at 5.17.10 PM.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/0edde2e8-941f-47eb-ab58-4d54ee16c827)

![Screen Shot 2021-04-06 at 5.17.27 PM.png](https://images.zenhubusercontent.com/5f970c483cdc923d98dfa265/ed17ff9d-0a9c-44f7-9181-15cc73f7cb8d)

**Comment by randyabramson** [comment]
This is great @AvivaOskow and @emilycryan 
Thank you!

@blaughman - one thing to note here is that we shouldn't use this as a 'reporting tool' (read: 23 Tagalog reports came in during the last two weeks) because of the way the Portal counts reports based on create date/new/open/closed (this is why Anthony does his magic on the export every two weeks).

In short, this is great to see ALL the reports in various languages, but if we want to count by exact date, we will need Anthony.

**Comment by randyabramson** [comment]
@blaughman if you are happy with this, we can move to CLOSED

**Comment by ilodidoj** [comment]
@randyabramson looking at this card for Moc reference. Please note, having "English" as default filter, intake specialist will miss any other language submission for a specific day. Recommended approach is to not have any language filter by default and let the intake user select the specific language filter when needed.  Please confirm if still "English" as default needed. If so, what would be the behavior of the view all table when the use clear all filter? current behavior is to remove all filters including any defaults.

**Comment by emilycryan** [comment]
@ilodidoj Because English is default, it should show automatically as a tile, just like what happens when you first open the screen and "new" and "open" are both selected and have visible tiles showing this as well. We wanted English selected bc 99% of the time, the specialist would be working in English and forcing them to open the MORE filter panel and change it to English every time they came in was way too much work. 

So the filter should be set by default and the tile should show, like in the mockup above. 

CC @blaughman @randyabramson

**Comment by randyabramson** [comment]
Good catch everyone...agree...no default language.

@emilycryan @blaughman @ilodidoj
